### ISSUE TITLE
Add DlrHost and DlrPort to Dlr Service Configuration

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-shared#11]
We need to extend the existing Grpc struct in our shared library to accommodate configuration for the DlrService. This is necessary as our microservices will utilize this shared library for gRPC communication.

Example usage:
```go
// Example usage for connecting to the Dlr service
conn, err := grpc.Dial(
    tconfig.GetInternalConfigInstance().Grpc.DlrHost + ":" + tconfig.GetInternalConfigInstance().Grpc.DlrPort,
    grpc.WithTransportCredentials(insecure.NewCredentials())
)
```
Modify the existing Grpc struct to include fields specific to the DlrService, such as DlrHost and DlrPort. 

You can locate the implementation of the DlrHost and port by examining the Grpc struct and looking for UserHost and UserPort.

**Comment by ebrarkesici** [comment]
I made the necessary changes here: https://github.com/octoposprime/op-be-shared/pull/12
